---
title: "sentinel_graphs"
author: "Sarah Tian"
date: "12/7/2021"
params:
  #base_dir: "/Users/weiyushitian/Documents/Latent_Lab/error_analysis/new"
  base_dir: "~/Desktop/glaciers/data/"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(tibble)
library(sf)
library(stringr)
library(superheat)
library(stringr)
```

```{r}
labels <- read_sf(file.path(params$base, "labels", "GL_3basins_2015.shp"))
metrics_combined <- read_csv(file.path(params$base, "metrics_combined.csv"))
metrics_avg <- read_csv(file.path(params$base, "metrics_average.csv")) 
```

```{r}
metrics_sentinel<-metrics_combined %>% 
  filter(dataset=="sentinel")

sentinel_max <- metrics_sentinel %>% 
  group_by(model,sample_id) %>% 
  slice(which.max(IoU))

sentinel_prob<-round(mean(sentinel_max$prob),1)#find the average prob corresponding to the max IoU

m_sentinel<-metrics_sentinel %>% 
  filter(prob==sentinel_prob) %>% 
  dplyr::select(-c(sample_id,filename)) %>%
  pivot_longer(-c(GL_ID,model,path,dataset,prob,test), names_to = "metric")

sentinel <- m_sentinel %>% filter(test=="False")
sentinel_test <- m_sentinel %>% filter(test=="True")
```

```{r}
i='IoU'
represent<-metrics_sentinel %>% 
  filter(test=="True") %>% 
  filter(prob==sentinel_prob) %>%
  dplyr::select(sample_id,model,i)%>% 
  pivot_wider(names_from = model, values_from = i) %>% 
  column_to_rownames(var = "sample_id") 

represent$variance = apply(represent[,1:length(colnames(represent))], 1, var)

represent<-represent %>% 
  rownames_to_column(var="sample_ID") %>% 
  mutate(GL_ID=substr(sample_ID, 0, 15)) %>% 
  arrange(variance) %>% 
  mutate(metric=i) %>%     
  mutate(quantile = ntile(metric, 5)) %>% 
  group_by(quantile) %>%
  sample_n(5) %>% 
  pivot_longer(c('test-delse-historical','test-delse','test-unet-historical','test-unet'),names_to = "model", values_to = "val") 

represent$model<-gsub("test-","",as.character(represent$model))

ggplot(represent %>% left_join(labels),aes(x=factor(model,level=c('unet','delse-historical','delse','unet-historical')),y=val))+
    geom_point(aes(size=Area))+
    geom_line(aes(group=GL_ID))+
    ggtitle(str_c(i," Across Models"))+
    theme(plot.title = element_text(hjust = 0.5),axis.title.x = element_blank())+
    scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
    NULL+
    facet_wrap(~quantile)

represent %>%
  rowwise() %>%
  mutate(path_prob=str_c(base,"/sentinel/sentinel_test-", model, "-images/", GL_ID,"_prob.png")%>% pander::pandoc.image.return())%>%
  mutate(path_prob=str_c(path_prob,'{height=1% width=1%}')) %>%
  mutate(model=str_c(model,'_prob')) %>%
  dplyr::select(-c(val,metric)) %>%
  pivot_wider(names_from = model,values_from = path_prob) %>%
  left_join(represent %>%
              rowwise() %>%
              mutate(path_pred=str_c(base,"/sentinel/sentinel_test-", model, "-images/", GL_ID, "_prob.png")%>% pander::pandoc.image.return()) %>%
              mutate(path_pred=str_c(path_pred,'{height=1% width=1%}')) %>% 
              mutate(model=str_c(model,'_pred')) %>%
              dplyr::select(-c(val,metric)) %>%
              pivot_wider(names_from = model,values_from = path_pred)) %>%
  dplyr::select("GL_ID", "quantile", "variance",'unet_prob','unet_pred','delse-historical_prob','delse-historical_pred','delse_prob','delse_pred','unet-historical_prob','unet-historical_pred') %>%
  dplyr::select(-c(quantile,variance)) %>% 
  pander(split.cells = c("50%", "10%", "10%","2.5%","2.5%","2.5%","2.5%","2.5%","2.5%","2.5%","2.5%"))
```


```{r}
set.seed(123)
metrics_long <- metrics_sentinel %>% 
  filter(
    (prob > 0.95 & model != "delse-historical") | (prob == 0.05 & model == "delse-historical") | model == "snake",
    subset %in% c("sentinel_recent_new", "sentinel_test")
  ) %>%
  mutate(GL_ID = str_extract(sample_id, "[:alnum:]+")) %>%
  pivot_longer(IoU:frechet, names_to="metric") %>%
  left_join(labels)

iou_quantiles <- metrics_long %>%
  filter(metric == "IoU") %>%
  group_by(sample_id, subset, label) %>%
  summarise(mean_value = mean(value)) %>%
  group_by(subset, label) %>%
  mutate(quantile = ntile(mean_value, 5))
  
metrics_long <- metrics_long %>%
  left_join(iou_quantiles %>% dplyr::select(sample_id, quantile))

sample_ids <- iou_quantiles %>%
  filter(subset %in% "sentinel_recent_new", label == "recent") %>%
  group_by(quantile) %>%
  sample_n(5)

subsample <- metrics_long %>%
  filter(sample_id %in% sample_ids$sample_id) %>%
  mutate(
    model = factor(model, c('unet', 'delse-historical', 'delse', 'snake', 'unet-historical')),
    metric = factor(metric, c("IoU", "precision", "recall", "frechet"))
    ) %>%
  filter(subset == "sentinel_recent_new", label == "recent")
```

```{r}
plot_subsample <- function(subsample, title) {
  ggplot(subsample, aes(model, value)) +
    geom_line(aes(group = sample_id, size = .5 * Area), col = "#A6A6A6") +
    geom_point(aes(size = Area), col = "#404040") +
    facet_grid(metric ~ quantile, scales = "free_y") +
    labs(
      size = "Lake Area (km ^ 2)",
      title = title,
      y = "Metric Value"
    ) +
    scale_size(range = c(.5, 5)) +
    scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
    theme(
      axis.text.x = element_text(size = 12),
      axis.title.x = element_blank(),
      strip.text.y = element_text(angle = 0),
      plot.title = element_text(size = 20)
    )
}

copy_images <- function(sample_ids, base_dir, output_dir="sentinel_quantiles") {
  for (qn in unique(sample_ids$quantile)) {
    cur_ids <- sample_ids %>%
      filter(quantile == qn) %>%
      pull(sample_id) %>%
      unique()
    qn_dir <- file.path(params$base_dir, "sentinel_preds", output_dir, qn)
    dir.create(qn_dir, recursive = TRUE)
  
    for (id in cur_ids) {
      cur_images <- list.files(
        file.path(params$base_dir, "sentinel_preds"), 
        str_c(id, "_pred*"), 
        recursive = TRUE,
        full = TRUE
      )
      
      for (im in cur_images) {
        im_path <- path_split(im)[[1]]
        cur_model <- im_path[length(im_path) - 1]
        model_dir <- file.path(qn_dir, cur_model)
        dir_create(model_dir)
        file.copy(im, model_dir, recursive = TRUE)
      }
    }
  }
}
```

```{r, fig.width = 14, fig.height = 8}
plot_subsample(subsample, "Metrics by Quantile (Sentinel, Labeled Recent Imagery)")
ggsave(file.path(params$base_dir, "quantiles_sentinel_recent.png"), dpi = 150)
copy_images(subsample, params$base_dir, "sentinel_quantiles_recent")
```

```{r, fig.width = 14, fig.height = 8}
sample_ids <- iou_quantiles %>%
  filter(subset %in% "sentinel_test", label == "ICIMOD") %>%
  group_by(quantile) %>%
  sample_n(5)

subsample <- metrics_long %>%
  filter(sample_id %in% sample_ids$sample_id) %>%
  mutate(
    model = factor(model, c('unet', 'delse-historical', 'delse', 'snake', 'unet-historical')),
    metric = factor(metric, c("IoU", "precision", "recall", "frechet"))
    ) %>%
  filter(subset == "sentinel_test", label == "ICIMOD")

plot_subsample(subsample, "Metrics by Quantile (Sentinel, Labels from 2015 provided by ICIMOD)")
ggsave(file.path(params$base_dir, "quantiles_sentinel_icimod.png"), dpi = 150)
copy_images(subsample, params$base_dir, "sentinel_quantiles_icimod")
```

